### ISSUE TITLE
[feat] 회원가입/로그인 API 구현

### ISSUE THREAD

**Issue by move-hoon** [NOW-SOPT-CDSP-WEB3/server#5]
## Issue 📌

- 회원가입/로그인 API를 구현합니다.
- 같은 이메일로 회원가입 하는 경우, 이메일 형식이 아닌경우 예외처리를 합니다.

## Todo ✔️

- [x]  POST 회원가입 요청 구현
- [x]  POST 로그인 요청 구현
- [x] 같은 이메일 회원가입, 이메일 형식 X 예외처리
